### PR TITLE
Support the two way binding operator "<=>"

### PR DESCRIPTION
**Pull request by Decodetalkers**

### CODE REVIEW

**Comment by Decodetalkers** [comment]
Sorry a mistake , set me as draft

**Comment by Decodetalkers** [comment]
Finished maybe

**Comment by jrmoulton** [comment]
Thanks for the PR!
It looks like this adds support for two way binding but only for callback aliases. There is probably a better way to get support for two way binding in all situations. A while ago I actually wrote a test suite for this parser but it didn't get merged here. I just pushed some commits with that test suite. I'll also add some CI so that the grammer.js file and tests are the only ones that need to be merged. 

With the changes I just pushed your changes to the grammer.js file are good to go and don't break any tests.  If you could either rebase and only commit the grammer.js file or just open a new PR with just the grammer.js file that would be awesome. After rebasing if you just want to merge you're changes to grammer.js as is that is good with me or you could add support for '<=>' in all situations. Either is good with me!

**Comment by jrmoulton** [comment]
Actually never mind about rebasing. These changes are good to go and I can merge them or if you want we can mark this as a draft until there is full support for the two way binding

**Comment by Decodetalkers** [comment]
> 

Emm, I want to know , except for callback ,does any place else use the <=> operator? I used to think that only callback use it..

**Comment by jrmoulton** [comment]
Yeah. Here in the lang-ref document there is more information. 
https://github.com/slint-ui/slint/blob/master/docs/langref.md#two-way-bindings

**Comment by Decodetalkers** [comment]
@jrmoulton  finished, please review it, thanks

**Comment by Decodetalkers** [comment]
And if your tests need help?

**Comment by Decodetalkers** [comment]
Hello? can you review it now?

**Comment by Decodetalkers** [comment]
@jrmoulton ping

**Comment by jrmoulton** [comment]
> Hello? can you review it now?

@Decodetalkers Did you see the review that I left about a week ago? I left a series of comments and suggestions.

**Comment by Decodetalkers** [comment]
> > Hello? can you review it now?
> 
> @Decodetalkers Did you see the review that I left about a week ago? I left a series of comments and suggestions.

I have already make changes

**Comment by jrmoulton** [comment]
I left comments and requests on the changes as a review and those haven't been addressed. One is the issue with pattern for identifiers. It actually needs to be a regex like 
```javascript
   _identifier: ($) => /[a-zA-Z_]([a-zA-Z_0-9-]?)+/,
```
I left more details as a review

**Comment by Decodetalkers** [comment]
> I left comments and requests on the changes as a review and those haven't been addressed. One is the issue with pattern for identifiers. It actually needs to be a regex like
> 
> ```js
>    _identifier: ($) => /[a-zA-Z_]([a-zA-Z_0-9-]?)+/,
> ```
> 
> I left more details as a review

Fixed

**Comment by jrmoulton** [comment]
Awesome! This looks great. 

Thanks for the contribution!

**Pull request merged**
